"""Add learner_style to User table

Revision ID: 951538718541
Revises: baf946ff421e
Create Date: 2026-03-18 14:26:57.270263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951538718541'
down_revision = 'baf946ff421e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutor_style', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learner_style', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('learner_style')

    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.drop_column('tutor_style')

    # ### end Alembic commands ###
