"""add tutor verification

Revision ID: 0f616053f817
Revises: 52363b47355b
Create Date: 2026-03-08 12:50:23.939430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f616053f817'
down_revision = '52363b47355b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
