"""Add TimeSlot and PasswordResetToken models, remove availability from Tutor

Revision ID: 2dd63eae2c72
Revises: f504f04388a7
Create Date: 2026-03-25 20:07:43.130142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd63eae2c72'
down_revision = 'f504f04388a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('time_block', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.drop_column('availability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('time_slots')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
